import Lait

/-!
# Automatic field accessors

A `type` with exactly one constructor also gets an accessor per named field: for
`(f : U)` on `T` with constructor `K`, `def T.f (self : T) : U := match self with
| K ... f ... => f end`.  Generated by `Surface.DeclEntry.mkGetters` in the
`type` case of `elabLaitDecl`, so they are ordinary `def`s.
-/

-- ===== Basics =====

{lait_decl getBasic
  type Foo := | MkFoo (x : Int) (y : Int) (z : Int)

  def f := MkFoo 1 2 3
  #test Foo.x f === 1
  #test Foo.y f === 2
  #test Foo.z f === 3

  -- Plain functions, so they can be passed around.
  def apply (g : Foo -> Int) (a : Foo) : Int := g a
  #test apply Foo.y f === 2
}

/-- info: Foo -> Int -/
#guard_msgs in
{lait_decl getBasicCheck
  type Foo := | MkFoo (x : Int) (y : Int)
  #check Foo.x
}

-- ===== Polymorphic types =====

-- Accessors are generalized over the type's parameters.
{lait_decl getPoly
  #include stdlib
  type Box<a, b> := | MkBox (one : a) (two : b) (tag : String)

  #test Box.one (MkBox 1 "s" "t") === 1
  #test Box.two (MkBox 1 "s" "t") === "s"
  #test Box.tag (MkBox 1 "s" "t") === "t"
  #test Box.one (MkBox "a" 0 "t") === "a"
  #test List.length (Box.one (MkBox [1, 2] 0 "t")) === 2
}

-- ===== When no accessors are generated =====

-- More than one constructor: no single arm to project out of.
{lait_decl getManyCtors
  type Two := | A (x : Int) | B (x : Int)
  #test (match A 1 with | A n => n | B n => n end) === 1
}

/-- error: Variable Two.x not found -/
#guard_msgs in
{lait_decl getManyCtorsNoAccessor
  type Two := | A (x : Int) | B (x : Int)
  #eval Two.x (A 1)
}

-- A nullary constructor generates nothing, which is not an error.
{lait_decl getNullary
  type Solo := | MkSolo
  #test MkSolo === MkSolo
}

-- `_` means "unnamed", so no accessor -- and, unlike a repeated real name, two
-- of them do not collide.
{lait_decl getUnderscore
  type Anon := | MkAnon (_ : Int) (named : Int) (_ : String)
  #test Anon.named (MkAnon 1 2 "s") === 2
}

/-- error: Variable Anon._ not found -/
#guard_msgs in
{lait_decl getUnderscoreNoAccessor
  type Anon := | MkAnon (_ : Int)
  #eval Anon._ (MkAnon 1)
}

-- ===== Corner cases =====

-- A field named `self` shadows the generated parameter inside the arm, so the
-- accessor still returns the field.
{lait_decl getSelfField
  type S := | MkS (self : Int)
  #test S.self (MkS 7) === 7
}

-- Recursive type: the result type mentions the type itself.
{lait_decl getRecursive
  #include stdlib
  type Chain := | MkChain (head : Int) (tail : Option<Chain>)
  def c := MkChain 1 (Some (MkChain 2 None))
  #test Chain.head c === 1
  #test (match Chain.tail c with
         | None => 0
         | Some t => Chain.head t
         end) === 2
}

-- Accessors are emitted after the whole mutual group, so one may return a
-- sibling type declared later.
{lait_decl getMutual
  #include stdlib
  type Expr := | MkExpr (op : String) (arg : Arg)
  and Arg := | MkArg (value : Int) (of_ : Option<Expr>)

  def e := MkExpr "neg" (MkArg 3 (Some (MkExpr "lit" (MkArg 0 None))))
  #test Expr.op e === "neg"
  #test Arg.value (Expr.arg e) === 3
  #test (match Arg.of_ (Expr.arg e) with
         | None => ""
         | Some inner => Expr.op inner
         end) === "lit"
}

-- A multi-constructor member of a group still gets none.
/-- error: Variable Shape.side not found -/
#guard_msgs in
{lait_decl getMutualManyCtors
  type Wrapper := | MkWrapper (shape : Shape)
  and Shape := | Square (side : Int) | Circle (radius : Int)
  #eval Shape.side (Square 1)
}

-- ===== `#include` =====

{lait_decl getLib
  type Pt := | MkPt (x : Int) (y : Int)
}

-- `Pt`'s accessors are spliced in along with it.
{lait_decl getClient
  #include getLib
  type Wrap := | MkWrap (inner : Pt) (label : String)

  def w := MkWrap (MkPt 3 4) "w"
  #test Pt.x (Wrap.inner w) === 3
  #test Pt.y (Wrap.inner w) === 4
  #test Wrap.label w === "w"
}

-- The stdlib's `Map` has one constructor, so it has an accessor too.
{lait_decl getStdlibMap
  #include stdlib
  #test List.length (Map.entries (Map.insert "a" 1 Map.empty)) === 1
}

-- ===== Two fields of the same name =====

-- Both would generate `Dup.x`; the uniqueness check rejects it.
/-- error: Dup.x is already defined -/
#guard_msgs in
{lait_decl getDupField
  type Dup := | MkDup (x : Int) (x : Int)
}

-- An alias has no constructors, so no accessors.
/-- error: Variable Pt.x not found -/
#guard_msgs in
{lait_decl getAliasNoAccessor
  type Pt := Int * Int
  #eval Pt.x (1, 2)
}
