[book]
title = "Lait Book"
authors = ["gancherj"]
language = "en"

[preprocessor.leandown]
command = "./node_modules/.bin/mdbook-leandown"

[output.html]
additional-js=["./node_modules/@leandown/mdbook/dist/index.js"]
additional-css=["./node_modules/@leandown/mdbook/dist/leandown.css"]